dataset_id: "2020"

paths:
  raw_file: "raw/2020_WO2020132269_raw.xlsx"
  bronze_dir: "bronze/2020"
  bronze_files:
    compounds: "bronze/2020/compounds.csv"
    assays: "bronze/2020/assays.csv"
    measurements: "bronze/2020/measurements.csv"
    panel_meta: "bronze/2020/panel_block_meta.csv"

schema:
  compounds:
    required: [compound_id, smiles_raw, dataset_id, provenance_file, provenance_sheet, provenance_row]
  assays:
    required: [assay_id, readout, matrix, label_raw]
  measurements:
    required: [compound_id, assay_id, value_raw, unit, censor, provenance_file, provenance_sheet, provenance_row]
    optional: [value_num, cell_line, assay_label, table_id, max_test_conc]
    id_keys: [compound_id, assay_id, cell_line, provenance_row]
  panel_meta:
    required: [table_id, assay_label, cell_lines, max_test_conc]

parsing:
  csv_read:
    dtype: "str"
    keep_default_na: false
    na_filter: false
  censor_map: {">": "gt", "<": "lt", "=": "eq"}
  unit_normalize:
    replacements:
      - ["μΜ", "μM"]
      - ["uM", "μM"]
  sci_notation:
    allow_e: true
    fix_te_to_e: true
  cell_line_map:
    "UMUC3": "UM-UC-3"
  assay_patterns:
    - sheet_regex: "Table\\s*2\\s*~\\s*4"
      columns: ["USP1 IC_50","USP1 IC50"]
      assign:
        target: "USP1"
        readout: "IC50_grade"
        matrix: "unknown"
        unit: "grade"
        allowed_values: ["+","++","+++","++++"]
  summary_tables:
    - sheet_regex: "Table\\s*5"
      columns:
        - {name: "Tissue", map_to: "tissue"}
        - {name: "Long term proliferation - USP1 inhibitor sensitive? (<316nM)", map_to: "longterm_sensitive"}
        - {name: "Colony Formation Assay - USP1 inhibitor sensitive? (<316nM)", map_to: "colony_sensitive"}
        - {name: "BRCA1", map_to: "brca1"}
        - {name: "BRCA2", map_to: "brca2"}
        - {name: "p53", map_to: "p53"}
        - {name: "ATM", map_to: "atm"}
      value_domain: {yes_no_na: ["Yes","No","-"]}
      notes: {threshold_note: "<316 nM"}
  legend_maps:
    solubility_grade:
      legend_sheet_regex: "Table\\s*6"
      levels: {"+": "< 10 µM", "++": "≥ 10 µM"}
    microsome_t_half_grade:
      legend_sheet_regex: "Table\\s*7"
      levels: {"+": "< 25 min", "++": "≥ 25 min"}
  string_normalization:
    mu_variants_to_muM: ["μΜ","uM"]

rules:
  bronze:
    keep_original: true
    split_censor: true
    allowed_units: ["μM", "mg/kg", null]
    max_test_conc_allowed: [2, 10]
  silver:
    enable: true
    target_units:
      cell: "μM"
      animal_dose: "mg/kg"
    transform:
      scale_rule_id: "SCL_CONC_V1"
      keep_censor: true
    identity_for_cell_um: true
    exclude_readouts: ["IC50_grade","solubility_grade","microsome_t_half_grade"]

qc:
  bad_id_regex: "^[0-9]+$"
  check_duplicates:
    pair:   [compound_id, assay_id]
    triplet: [compound_id, assay_id, cell_line]
  outputs:
    dir: "bronze/2020"
    files:
      - "qc_bad_compound_id.csv"
      - "qc_dup_pair.csv"
      - "qc_dup_triplet.csv"
      - "qc_missing_assay_id.csv"
      - "qc_nonstandard_cell_label.csv"
      - "qc_overall.md"
  require_allowed_values:
    - {column: "USP1 IC50", allowed: ["+","++","+++","++++"]}
  note_fields_must_exist: ["threshold_note"]
