dataset_id: "2018"

paths:
  raw_file: "raw/2018_raw.xlsx"
  bronze_dir: "bronze/2018"
  bronze_files:
    compounds: "bronze/2018/compounds.csv"
    assays: "bronze/2018/assays.csv"
    measurements: "bronze/2018/measurements.csv"
    panel_meta: "bronze/2018/panel_block_meta.csv"

schema:
  compounds:
    required: [compound_id, smiles_raw, dataset_id, provenance_file, provenance_sheet, provenance_row]
  assays:
    required: [assay_id, readout, matrix, label_raw]
  measurements:
    required: [compound_id, assay_id, value_raw, unit, censor, provenance_file, provenance_sheet, provenance_row]
    optional: [value_num, cell_line, assay_label, table_id, max_test_conc, meas_kind, limit]
    id_keys: [compound_id, assay_id, cell_line, provenance_row]
  panel_meta:
    required: [table_id, assay_label, cell_lines, max_test_conc]

parsing:
  csv_read:
    dtype: "str"
    keep_default_na: false
    na_filter: false
  censor_map: {">": "gt", "<": "lt", "=": "eq"}
  unit_normalize:
    replacements:
      - ["μΜ", "μM"]
      - ["uM", "μM"]
  sci_notation:
    allow_e: true
    fix_te_to_e: true
  assay_patterns:
    - columns: ["KRAS-SOS1 Interaction","KRAS-Activation by SOS high GTP","KRAS-Activation by SOS no GTP"]
      assign:
        target: "KRAS/SOS1"
        readout: "mixed"
        matrix: "biochemical"
        unit_base: "M"
        meas_kind_percent: "percent_inhibition_@20uM"
        meas_kind_numeric: "IC50"
        right_censor_limit: 2.0e-5
    - columns: ["EGFR kinase inhibition IC50"]
      assign:
        target: "EGFR"
        readout: "IC50"
        matrix: "enzyme"
        assay_type: "kinase"
        unit_base: "M"
        right_censor_limit: 2.0e-5
  string_normalization:
    mu_variants_to_muM: ["μΜ","uM"]

rules:
  bronze:
    keep_original: true
    split_censor: true
    allowed_units: ["M", "μM", null]
  silver:
    enable: true
    target_units:
      IC50: "μM"
    transform:
      scale_rule_id: "SCL_CONC_V1"
      keep_censor: true

qc:
  bad_id_regex: "^[0-9]+$"
  check_duplicates:
    pair:   [compound_id, assay_id]
    triplet: [compound_id, assay_id, cell_line]
  outputs:
    dir: "bronze/2018"
    files:
      - "qc_bad_compound_id.csv"
      - "qc_dup_pair.csv"
      - "qc_dup_triplet.csv"
      - "qc_missing_assay_id.csv"
      - "qc_nonstandard_cell_label.csv"
      - "qc_overall.md"
