dataset_id: "2021"

paths:
  raw_file: "raw/2021_raw.xlsx"
  bronze_dir: "bronze/2021"
  bronze_files:
    compounds: "bronze/2021/compounds.csv"
    assays: "bronze/2021/assays.csv"
    measurements: "bronze/2021/measurements.csv"
    panel_meta: "bronze/2021/panel_block_meta.csv"

schema:
  compounds:
    required: [compound_id, smiles_raw, dataset_id, provenance_file, provenance_sheet, provenance_row]
  assays:
    required: [assay_id, readout, matrix, label_raw]
  measurements:
    required: [compound_id, assay_id, value_raw, unit, censor, provenance_file, provenance_sheet, provenance_row]
    optional: [value_num, cell_line, assay_label, table_id, max_test_conc]
    id_keys: [compound_id, assay_id, cell_line, provenance_row]
  panel_meta:
    required: [table_id, assay_label, cell_lines, max_test_conc]

parsing:
  assay_patterns:
    - columns:
        - "PRMT5 MTase Glo Ki (nM, Meth. A)"
        - "PRMT5 MTase Glo Ki (nM, Meth. B)"
      assign:
        assay_id_from_header:
          pattern: 'PRMT5 MTase Glo Ki \(nM, Meth\. (?P<method>[AB])\)'
        target: "PRMT5"
        readout: "Ki"
        matrix: "enzyme"
        unit: "nM"
    - columns:
        - "Prolif HCT116–MTAP null IC50 (μM)"
        - "Prolif HCT116–WT IC50 (μM)"
      assign:
        assay_id_from_header:
          pattern: 'Prolif HCT116[\-–](?P<genotype>MTAP null|WT) IC50 \((?:μ|u)M\)'
        target: "PRMT5"
        readout: "IC50"
        matrix: "cell"
        unit: "μM"
        extras:
          cell_line: "HCT116"
  string_normalization:
    mu_variants_to_muM: ["μΜ","uM"]
    ic50_typos_to_IC50: ["ICso","IC_so","lC50"]
    cell_line_map: {"HCTl16":"HCT116","HCTU6":"HCT116","HCTI16":"HCT116"}
  value_parser:
    pattern: "^(?P<censor>>=|>|<=|<)?\\s*(?P<value>\\d+(?:\\.\\d+)?)$"
    fields: {censor_field: "censor", value_field: "value_num"}
  csv_read:
    dtype: "str"
    keep_default_na: false
    na_filter: false
  censor_map: {">": "gt", "<": "lt", "=": "eq"}
  unit_normalize:
    replacements:
      - ["μΜ", "μM"]
      - ["uM", "μM"]
  sci_notation:
    allow_e: true
    fix_te_to_e: true
  cell_line_map:
    "UMUC3": "UM-UC-3"

rules:
  bronze:
    keep_original: true
    split_censor: true
    allowed_units: ["μM", "mg/kg", null]
    max_test_conc_allowed: [2, 10]
  silver:
    enable: true
    target_units:
      cell: "μM"
      animal_dose: "mg/kg"
      Ki: "nM"
      IC50: "μM"
    transform:
      scale_rule_id: "SCL_CONC_V1"
      keep_censor: true
    identity_for_cell_um: true
    identity_rules:
      - when: {matrix: "enzyme", readout: "Ki"}
      - when: {matrix: "cell", readout: "IC50"}

qc:
  bad_id_regex: "^[0-9]+$"
  check_duplicates:
    pair:   [compound_id, assay_id]
    triplet: [compound_id, assay_id, cell_line]
  outputs:
    dir: "bronze/2021"
    files:
      - "qc_bad_compound_id.csv"
      - "qc_dup_pair.csv"
      - "qc_dup_triplet.csv"
      - "qc_missing_assay_id.csv"
      - "qc_nonstandard_cell_label.csv"
      - "qc_overall.md"
  expected_columns:
    - "PRMT5 MTase Glo Ki (nM, Meth. A)"
    - "PRMT5 MTase Glo Ki (nM, Meth. B)"
    - "Prolif HCT116–MTAP null IC50 (μM)"
    - "Prolif HCT116–WT IC50 (μM)"
  fail_on_unknown_matrix: true
  check_value_censor: [">","<",">=","<="]
